



* 05/13/2015
** how to deal with keyboard layout changing
loadkeys, dumpkeys and showkeys are used
*** 1. Save your current keyboard layout
$ dumpkeys > backup.kmap
In case something goes wrong you might be able restore your keymap using the command:
$ sudo loadkeys backup.kmap
If the keyboard is so messed up that you can't even do this then your only option not involving ancient kernel magic is to reboot
*** 2. Check which keycodes are assigned to your keys
$ showkey
Now press the ESC key and the CAPSLOCK key. The keycodes should showup on the screen.
Note the keyodes. On my system the ESC has the keycode 1 and CAPSLOCK has the keycode 58. "showkey" will terminate after 10 seconds of inactivity
*** 3. Note the names of the ESC and CAPSLOCK keys from dumpkeys
$ dumpkeys | grep 1
...
keycode 1 = Escape
...
$ dumpkeys | grep 58
...
keycode 58 = CtrlL_Lock
...
*** 4. Note the keymap line from dumpkeys
$ dumpkeys | head -1
keymaps 0-127
*** 5. Create a keymap file which switches ESC and CAPSLOCK
keymaps 0-127
keycode 1 = CtrlL_Lock
keycode 58 = Escape
*** 6. Load the keymap
$ sudo loadkeys swap_esc_capslock.kmap
*** 7. Test 
Testing the CAPSLOCK key is obvious. Just press the CAPSLOCK key and check whether other keys come out capitalized. To test the ESC key you can use CTRL+V followed by ESC. It should print "^[". CTRL+V makes the shell print the next key verbatim instead of interpreting it.
*** 8. To have this modification load every reboot, put the following line in your /etc/rc.local line:
/usr/bin/loadkeys /path/to/swap_esc_capslock.kmap


* many days ago when I installed this debian
# This computer is debian version linux
I have installed it but I have no idea what I use it to do
So it may be dropped in someplace until oneday using it as a server


